### ISSUE TITLE
Hardcoded jaeger path

### ISSUE THREAD

**Issue by EinKrebs** [pavolloffay/jaeger-clickhouse#11]
Make considers path to jaeger all-in-one as `${HOME}/projects/jaegertracing/jaeger/cmd/all-in-one/all-in-one-linux-amd64`, maybe it's better to make environmental variable for this

**Comment by pavolloffay** [comment]
The path is configurable like the readme says https://github.com/pavolloffay/jaeger-clickhouse#run

**Comment by pavolloffay** [comment]
We should change the run command to run Jaeger all-in-one from docker and inject the compiled plugin via volume.

**Comment by pavolloffay** [comment]
Something like this could work, but it doesn't. I didn't dig into it.

```
.PHONY: run
run:
	docker run --rm -it -u ${shell id -u} -v "${PWD}:/data" -e SPAN_STORAGE_TYPE=grpc-plugin jaegertracing/all-in-one:1.24.0 --grpc-storage-plugin.binary=/data/jaeger-clickhouse-$(GOOS)-$(GOARCH) --grpc-storage-plugin.configuration-file=/data/config.yaml
	#SPAN_STORAGE_TYPE=grpc-plugin ${JAEGER_ALL_IN_ONE} --grpc-storage-plugin.binary=./jaeger-clickhouse-$(GOOS)-$(GOARCH) --grpc-storage-plugin.configuration-file=./config.yaml

```
