### ISSUE TITLE
Create "tutorial" with sharding and replication and HA setup

### ISSUE THREAD

**Issue by pavolloffay** [pavolloffay/jaeger-clickhouse#28]
Disclaimer I am just starting with Clickhouse. 

As far as I can tell our scripts https://github.com/pavolloffay/jaeger-clickhouse/blob/main/sqlscripts/0002-jaeger-spans.sql create only local tables and not distributed ones so this tutorial will likely need different scripts.

**Comment by EinKrebs** [comment]
As far as I know, sharding and replication are implemented by database engine, settings of sharding and replication are server-sided, so it's not needed to do anything with SQL scripts.

More info [here](https://cloud.yandex.ru/docs/managed-clickhouse/tutorials/sharding)

**Comment by pavolloffay** [comment]
I think the engine on the tables has to be changed.

**Comment by EinKrebs** [comment]
Oh, I forgot that it's on our side, sorry for desinformation
