### ISSUE TITLE
Implement dependency store

### ISSUE THREAD

**Issue by EinKrebs** [pavolloffay/jaeger-clickhouse#30]

**Comment by pavolloffay** [comment]
This is more tricky. Let me explain why. 

The dependency links are not created in the jaeger-collector but in an external process. This process aggregates spans and calculates which links should be created. It directly accesses the storage. 

The implementation is here https://github.com/jaegertracing/spark-dependencies

So to support dep. links we would have to add support for clickhouse to spark-dependencies. Or maybe there is a way to implement it directly in the storage (e.g. via view) but I cannot confirm that.
