### ISSUE TITLE
Make replicated deployment work without user explicitly creating tables  

### ISSUE THREAD

**Issue by pavolloffay** [pavolloffay/jaeger-clickhouse#39]
The https://github.com/pavolloffay/jaeger-clickhouse/blob/main/guide-sharding-and-replication.md#replication requires uses to run SQL scripts on one node (bc we use `ON CLUSTER`). 

We could add a new config option `replication: true` that would indicate that replication is enabled. The plugin would then use 
* `ON CLUSTER` 
* replicated merge trees in local tables
* create global tables

cc) @EinKrebs is this smth that interests you?

**Comment by EinKrebs** [comment]
@pavolloffay yes, I'm gonna do this

**Comment by EinKrebs** [comment]
@pavolloffay should I add options for global table names too? I think it will be consistent.

**Comment by pavolloffay** [comment]
> should I add options for global table names too? 

There is already config to define the table names. We could automatically remove the `local` suffix if replication is enabled.

**Comment by EinKrebs** [comment]
Custom database names may not end with ``_local``. Maybe it's better to automatically add it than to remove.

**Comment by pavolloffay** [comment]
> Custom database names may not end with _local. Maybe it's better to automatically add it than to remove.

Why not? As far as I understand CH they will be local, but replicated. 

The current config exposes options to set table names that are used in reader and writer. I don't see why we need another set of options for table names.

**Comment by pavolloffay** [comment]
Done in #53
