### ISSUE TITLE
Change batch writing policy

### ISSUE THREAD

**Issue by EinKrebs** [pavolloffay/jaeger-clickhouse#58]
Currently, we insert batch by one span. But for ClickHouse, it's better to insert big amounts of data.

**Comment by EinKrebs** [comment]
Also, if we write huge amounts of data, it's impossible not to repeat failed transactions. So, we need to figure something out.

**Comment by EinKrebs** [comment]
Ok, I take my words back, It's clickhouse-go driver feature, and actually data's written by big amounts.

**Comment by pavolloffay** [comment]
one question, could we remove the internal batching (time and size) and depend on the driver?

**Comment by EinKrebs** [comment]
No. Driver makes it possible to prepare statement, then execute it many times in one transaction, and it will be written in one bulk.
